### ISSUE TITLE
Missing setup.py

### ISSUE THREAD

**Issue by fabianvdW** [kiudee/chess-tuning-tools#103]
Can not make/install locally because of missing setup.py, or do I not understand something?

**Comment by kiudee** [comment]
The chess-tuning-tools package is defined using the `pyproject.toml` file (which is kind of the inofficial successor to setup.py).
If you just want to use the library, it is easiest to install it using
```bash
pip install chess-tuning-tools
```

If you want to install the the most recent version from git, I recommend following the steps here:
https://chess-tuning-tools.readthedocs.io/en/latest/contributing.html#get-started


Let me know if there are any problems on the way.

**Comment by fabianvdW** [comment]
Okay, I was just confused because of the docs: https://chess-tuning-tools.readthedocs.io/en/latest/installation.html#from-sources

**Comment by kiudee** [comment]
Oh, indeed. That was not updated. Thank you!
