### ISSUE TITLE
Hard ELO Losing Optimum for StockNemo

### ISSUE THREAD

**Issue by TheBlackPlague** [kiudee/chess-tuning-tools#209]
* Chess Tuning Tools version: 0.9.2
* Python version: 3.8.10
* Operating System: Ubuntu 20.04

### Description

I started tuning two parameters and about 130 iterations. When it finished, the optimum values it gave were extremely bad and lose a lot of ELO. From an SPRT test with them vs. the base values:

Base Values:
```
NULL_MOVE_REDUCTION = 3
NULL_MOVE_DEPTH = NULL_MOVE_REDUCTION - 1
```
Optimum Values from Chess Tuning Tools:
```
NULL_MOVE_REDUCTION = 6
NULL_MOVE_DEPTH = 14
```

Optimum vs Base:
```
ELO   | -48.42 +- 16.89 (95%)
SPRT  | 10.0+0.10s Threads=1 Hash=16MB
LLR   | -2.99 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 1040 W: 254 L: 398 D: 388
```

My engine is available at: https://github.com/TheBlackPlague/StockNemo (in case you wanna snoop around in the source code).

### What I Did

Here's the necessary configuration used for the tuning:
```json
{
    "engines": [
        {
            "command": "StockNemoTUNE",
            "fixed_parameters": {
                "Hash": 16
            }
        },
        {
            "command": "StockNemoNOTUNE",
            "fixed_parameters": {
                "Hash": 16
            }
        }
    ],
    "parameter_ranges": {
        "NullMoveReduction": "Integer(0, 16)",
        "NullMoveDepth": "Integer(0, 16)"
    },
    "engine1_tc": "5+0.05",
    "engine2_tc": "5+0.05",
    "opening_file": "UHO_XXL_+0.90_+1.19.epd",
    "rounds": 128,
    "concurrency": 64,
    "adjudicate_draws": true,
    "draw_score": 10,
    "draw_movenumber": 40,
    "draw_movecount": 4,
    "adjudicate_resign": true,
    "resign_score": 400,
    "resign_movecount": 4,
    "result_every": 500,
    "plot_every": 500,
    "plot_path": "plots",
    "acq_function": "pvrs",
    "acq_function_samples": 0,
    "gp_burnin": 3,
    "gp_initial_burnin": 200,
    "n_initial_points": 32,
    "random_seed": 836717
}
```

Maybe I did something wrong in the configuration? Please suggest changes if you believe so.

Command ran: `tune local -c tune.json` with `tune.json` available above.

The code being tuned is:
https://github.com/TheBlackPlague/StockNemo/blob/9842e5718ed65da9c9ef9dfd3efa065ea5278c3c/Backend/Engine/MoveSearch.cs#L322-L343

**Comment by kiudee** [comment]
Could you share the model.pkl, data.npz files and the latest plots (if available)?

That will make it easier to debug.

**Comment by TheBlackPlague** [comment]
> Could you share the model.pkl, data.npz files and the latest plots (if available)?
> 
> That will make it easier to debug.
> 
> Edit: the log file would also be useful.

The model.pkl and data.npz files are no longer available, I'm afraid. I deleted them 😞 .

However, the landscape plot is available:
![landscape-20220727-011746-130](https://user-images.githubusercontent.com/44123859/181215108-0703acbc-a1f0-4879-9233-9ca5ff883652.png)

**Comment by TheBlackPlague** [comment]
@kiudee To update you, in all honesty, there may have been an error on my part. 

I'm retrying the same tune with recompiled binaries of the engines. I'll update you on that and provide you with the necessary debug files that way, too, if the issue still persists. 

Thank you for taking the time to respond.

**Comment by kiudee** [comment]
Thanks for the update.

Looking at the landscape, the partial dependence ranges from 0.012 to 0.022. You can multiply this by 100 to get roughly an estimated Elo difference of 1 Elo point. So either the parameters in question have a very small effect or the parameters are in some way not set correctly (which happened to me and others as well).

**Comment by TheBlackPlague** [comment]
I've retested it all and done the tuning to 221 epochs. Please see the following plot:
![landscape-20220727-144145-221](https://user-images.githubusercontent.com/44123859/181391871-554807ac-ad71-46cc-995b-8d8ba78a8962.png)

Moreover, if you need the log and other files, I can also attach them.

**Comment by kiudee** [comment]
This landscape looks much more plausible. You can see that if NullMoveReduction is set to 0, it results in a reduction of >300 Elo points.

What I would do here is to zoom into the most promising region by setting the ranges to something like
```json
    "parameter_ranges": {
        "NullMoveReduction": "Integer(1, 8)",
        "NullMoveDepth": "Integer(0, 6)"
    },
```
The sharp peak for `NMR=0` could be problematic by sharply pulling the landscape up.

chess-tuning-tools supports zooming in without problems. You can just change those values and continue running the tune. Just in case backup the `model.pkl` and `data.npz` before.

You can also let the tuner evaluate the current default values, by creating a csv file with the following contents:
```csv
3,2,128
```
If those values coincide with the engine you tune against, this should result in close to 0 Elo and bias the tuner.

**Comment by TheBlackPlague** [comment]
> This landscape looks much more plausible. You can see that if NullMoveReduction is set to 0, it results in a reduction of >300 Elo points.
> 
> What I would do here is to zoom into the most promising region by setting the ranges to something like
> 
> ```json
>     "parameter_ranges": {
>         "NullMoveReduction": "Integer(1, 8)",
>         "NullMoveDepth": "Integer(0, 6)"
>     },
> ```
> 
> The sharp peak for `NMR=0` could be problematic by sharply pulling the landscape up.
> 
> chess-tuning-tools supports zooming in without problems. You can just change those values and continue running the tune. Just in case backup the `model.pkl` and `data.npz` before.
> 
> You can also let the tuner evaluate the current default values, by creating a csv file with the following contents:
> 
> ```
> 3,2,128
> ```
> 
> and adding `--evaluate-points file.csv` to the tune call. If those values coincide with the engine you tune against, this should result in close to 0 Elo and bias the tuner.

Thank you for your response. Everything you said makes perfect sense. Thank you for writing it out in an understandable manner.

I agree that `NMR=0` could be problematic, but that was the idea of leaving it there. Essentially, I wanted the tuner to learn that having a 0 value for that would be extremely problematic and to avoid it at all costs. 

Is tuning better in a way if I leave bad values in first, let it run a couple of iterations, and then use good values? What would you suggest?

**Comment by kiudee** [comment]
In general I would try to remove pathological cases on the boundary (for example where a specific value turns a feature off). The tuner is trying to learn a smooth Elo landscape, so one should avoid giving it points which correspond to discontinuities.

Bad regions are not problematic in general though and one needs to decide on a case by case basis, if a certain region is not representative of the whole landscape.

In your specific case I would leave out `NMR=0` from the tuning range.

**Comment by TheBlackPlague** [comment]
Thanks a lot @kiudee for the clarification. Very much appreciated. 👍
