### ISSUE TITLE
Documentation of dbconfig.json missing

### ISSUE THREAD

**Issue by Claes1981** [kiudee/chess-tuning-tools#31]
* Chess Tuning Tools version: 0.3.0
* Python version: 3.8.3
* Operating System: Linux OpenSUSE Tumbleweed with Python 3 virtual environment venv

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

Trying to run the tuning tools locally to experiment with UCI settings of various engines. 

The experiment.json configuration file that the tuning server needs is documented by an example in the examples directory. However, I can not find the dbconfig.json file, that it also requires, documented anywhere, so I do not know what it should contain. The starting command fails without a dbconfig.json file, which I assume is needed for the communication with the client.
It would be good to have an example also of the dbconfig.json in the examples directory.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```
(env) bash-5.0$ tune run-server run experiment.json
Usage: tune run-server [OPTIONS] COMMAND EXPERIMENT_FILE DBCONFIG
Try 'tune run-server --help' for help.

Error: Missing argument 'DBCONFIG'.

**Comment by kiudee** [comment]
In order to use the distributed tuning framework, you need to pass a json file containing the fields:
- `user`
- `password`
- `host` (the url to the postgreSQL server)
- `port`
- `dbname` (the name of the database)

Should you only be interested in using the package to tune a chess engine locally on your machine, this is probably overkill. A simplified script is in the works, but is not contained in this library yet.

Regarding the issue itself, I agree that the dbconfig.json file should be properly documented.

**Comment by Claes1981** [comment]
Thanks,

Overkill is at least better than something that does not work I think. 
I have, for example, tried CLOP of Rémi Coulom with 4 parameters, but I can not get it to converge. (It test the exact same few samples over and over again, but one eigenvalue remain clear positive.) And the SPSA-implementations I have found seems to not work for parameters that need to be integers.

I tried a dbconfig.json that looks like this:

```
[
    {
        "user": "claes",
        "password": "test",
        "host": "http://localhost",
        "port": "5432",
        "dbname":"test"
    }
]
```

Now it returns a "Traceback" instead (when testing together with the "experiment.json"-example.) :

```
(env) bash-5.0$ tune run-server run experiment.json dbconfig.json
Traceback (most recent call last):
  File "/home/claes/Chess-tuning-tools/env/bin/tune", line 8, in <module>
    sys.exit(cli())
  File "/home/claes/Chess-tuning-tools/env/lib64/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/claes/Chess-tuning-tools/env/lib64/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/claes/Chess-tuning-tools/env/lib64/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/claes/Chess-tuning-tools/env/lib64/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/claes/Chess-tuning-tools/env/lib64/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/claes/Chess-tuning-tools/env/lib64/python3.8/site-packages/tune/cli.py", line 56, in run_server
    tc = TuningServer(experiment_path=experiment_file, dbconfig_path=dbconfig)
  File "/home/claes/Chess-tuning-tools/env/lib64/python3.8/site-packages/tune/db_workers/tuning_server.py", line 53, in __init__
    self.engine = create_sqlalchemy_engine(self.connect_params)
  File "/home/claes/Chess-tuning-tools/env/lib64/python3.8/site-packages/tune/db_workers/utils.py", line 66, in create_sqlalchemy_engine
    f"postgresql://{config['user']}:{config['password']}"
TypeError: list indices must be integers or slices, not str

```

**Comment by rosenthj** [comment]
I was able to progress by modifying Claes file to the following dbconfig file.
```
{
  "user": "jonathan",
  "password": "test",
  "host": "localhost",
  "port": "5432",
  "dbname":"test"
}
```
This lead to another issue I am unsure how to resolve.
```
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
```

**Comment by Claes1981** [comment]
Thanks for the dbconfig suggestion, I am now also able proceed to the same error message as you.

Maybe we also need to in some way create and manually start a PostgreSQL server on our computers.

**Comment by kiudee** [comment]
Yes, you need a running database server for the distributed tuning setup.

A local tuning script is currently work-in-progress and could be used to replace CLOP for tuning.

**Comment by Claes1981** [comment]
Sounds interesting. I am impressed by your tuning of Lc0 and the various postings on Lc0 Discord channel with the informative graphs from your Bayes-skopt tool.
Can't find out how to connect Bayes-skopt to Cutechess-cli though.

**Comment by kiudee** [comment]
Began migrating my scattered script code into properly tested and documented functions in pull request #32. I hope I can finish the first working version soon.

**Comment by kiudee** [comment]
Closing this for now since the project is focusing on polishing up the standalone (local) tuning script.
