### ISSUE TITLE
Support changing the prior parameters

### ISSUE THREAD

**Issue by kiudee** [kiudee/chess-tuning-tools#38]

**Comment by Claes1981** [comment]
I tried implementing the setting of prior parameters before, se currently commented out lines:
https://github.com/Claes1981/chess-tuning-tools/blob/7a62264ae6eb6bc873e39bdadd635b9a37ba08df/tune/cli.py#L202-L225
https://github.com/Claes1981/chess-tuning-tools/blob/7a62264ae6eb6bc873e39bdadd635b9a37ba08df/tune/cli.py#L384-L398
https://github.com/Claes1981/chess-tuning-tools/blob/7a62264ae6eb6bc873e39bdadd635b9a37ba08df/tune/cli.py#L405

However I couldn't get it to work, it seems the `gp_priors=priors` parameter gets the wrong format. I feel I lack sufficient Python knowledge to figure out how it should be done.

**Comment by kiudee** [comment]
I am currently in the process of refactoring the cli.py file to make it much easier to read, maintain and test. Afterwards the plan is to implement support for changing the relevant prior parameters.

Regarding your changes:
```python
lambda x: roundflat(np.exp(x)) + x for _ in range(len(list(param_ranges.values()))),
```
This looks like it should be something like:
```python
*[lambda x: roundflat(np.exp(x)) + x for _ in range(len(list(param_ranges.values())))],
```

**Comment by Claes1981** [comment]
Thanks, I might try it this weekend.
