### ISSUE TITLE
Documentation for the parameters

### ISSUE THREAD

**Issue by kiudee** [kiudee/chess-tuning-tools#65]
It is unclear what all the parameters in 
https://github.com/kiudee/chess-tuning-tools/blob/master/examples/complete_config.json
are doing. Some of these parameters have a short description when running `tune local --help`, but it would be nice to have a comprehensive documentation about what these parameters do.

**Comment by kiudee** [comment]
Fixed by #68

**Comment by Claes1981** [comment]
Trying to figure out if some of the tuner's model-related parameters might in some cases reduce the number of iterations required to reach a given confidence interval of optimized UCI parameters.

Personally especially interested in the case of more than 5 optimized parameters (dimensions) and 2 games per iteration (and long time control).

According to [Bask documentation](https://bayes-skopt.readthedocs.io/en/latest/modules/generated/bask.Optimizer.html#bask.Optimizer), regarding gp_samples: "More samples result in a more accurate representation of the hyperposterior", and regarding gp_burnin: "Only needs to be increased, if the hyperposterior after burnin has not settled on the typical set".

Not knowing much about Gaussian Processes, I guess the "hyperposterior" might have something to do with the hyperparameters of the model of how the optimized parameters influence Elo. Would you try to increase any of gp-samples or gp-burnin in my case (>5 dimensions, 2 games/iteration, long time control)?

If the tuning process is aborted and resumed frequently, will the corresponding gp-initial-samples and gp-initial-burnin parameters be worth changing too?

If all those model-related parameters might be worth changing in specific tuning setups (low or high number of optimized UCI parameters, games per iteration, frequency of resuming, etc), it would be nice to have some comments in the [Parameter Reference page](https://chess-tuning-tools.readthedocs.io/en/latest/parameters.html) about which setups each model-related parameter might be changed for. 

Current experiment log so far:
[Stockfish_20080713_bmi2_pgo_S200728-1442_b.log](https://github.com/kiudee/chess-tuning-tools/files/5147016/Stockfish_20080713_bmi2_pgo_S200728-1442_b.log)

**Comment by kiudee** [comment]
If you want to get the maximum information out of each iteration and don’t care too much about runtime (since you run long matches), I would set `gp_burnin` to at least 100. That should allow it ample iterations to settle on the new best parameter region. The way `gp_samples` is currently implemented (without thinning), it does not make too much sense to increase it a lot, since most of the samples will be correlated. The default should be fine.

Same thing is true for `gp_initial_burnin`. With a value of 100-200 you should have reached the correct region.

**Comment by Claes1981** [comment]
Thank you very much for your advice :)

**Comment by kiudee** [comment]
> Does it matter how many iterations are completed before, if resuming?

No, it does not matter.
> Can you set gp-burnin higher than completed iterations (=samples)?

`gp-burnin` is set in terms of sampling iterations, each of which would constitute 100 samples. Yes, you can set it as high as you want. But as soon as the Markov chain has reached the typical set, any further burnin is pointless.

> Maybe "Number of samples to discard" does not refer to samples of match results?
Yes, this is completely unrelated to the chess matches.

**Comment by Claes1981** [comment]
Okay, thanks. I set gp-burnin and gp-inital-burnin to 200. It takes about 2-3 minutes then to update the model between iterations on my 4 core laptop,  which I find acceptable.
