### ISSUE TITLE
Feature proposal: support for Cutechess-cli st (time per move) time control

### ISSUE THREAD

**Issue by Claes1981** [kiudee/chess-tuning-tools#69]
With the Cutechess-cli `st=` option you can set a fixed number of seconds for the engine per move, without the engine being able to save time for later moves.

I think it is interesting to find out which engine, or engine version, is the strongest at analyzing (important) game positions (in a given time), without the engine's time management capabilities affecting the results. I think that can be better measured with the "st" time control, where the time management should be less important.
I find it interesting because, if you use the engine for analyzing positions of real games, it is hard (at least for me) to determine if it is a position that the engine would have spent extra time at if it was a game it played, and the analysis therefore might not be as good as expected, unless you also let the engine think extra long at that move when analyzing. Especially if you let some software automatically analyze all moves of a game, I think the engine will spend about the same time at each move, not very correlated to the time it would spend in a real game.

It would be interesting to also be able to experiment with the tuning of an engines parameters in the Chess-tuning-tools under those time conditions (no saving of time between moves), to possibly increase it's performance under those conditions.
Not sure how good the already implemented nodes per move option would be for this case, compared to a time per move setting. (I guess some parameters might affect the speed in nodes per second of an engine...)

* Chess Tuning Tools version: 0.5.1
* Python version: 3.8.3
* Operating System: OpenSUSE Tumbleweed

**Comment by kiudee** [comment]
Good idea and also quite easy to implement. I think it would be interesting to see how certain search parameters are favored, if the engine does not have to worry about time management, but the search speed still matters (in comparison to fixed nodes tuning).
