### ISSUE TITLE
Console output tweaks for smoother monitoring

### ISSUE THREAD

**Issue by AlexisOlson** [kiudee/chess-tuning-tools#86]
1. If possible, print the game results as they come in rather than all at once when all the rounds are complete.

2. Allow user to suppress some of the debug output in the console (still fine to keep in the log file), particularly the `vmin` and `ticklocs array` lines that take up so much space.

3. Show confidence intervals and estimated value every iteration (even if they haven't changed) so the it stays visible without requiring scrolling.

**Comment by kiudee** [comment]
> 
> 
>     1. If possible, print the game results as they come in rather than all at once when all the rounds are complete.

I will investigate how difficult this would be to do. I don’t expect it to be problematic.

> 
>     2. Allow user to suppress some of the debug output in the console (still fine to keep in the log file), particularly the `vmin` and `ticklocs array` lines that take up so much space.

Indeed, I did notice that too late. Somehow the plotting library spams a lot of debug output when using log-scales. Planning to fix that (issue #70).

> 
>     3. Show confidence intervals and estimated value every iteration (even if they haven't changed) so the it stays visible without requiring scrolling.

That is already possible by setting:
```
"result_every": 1
```
