### ISSUE TITLE
Get the best values

### ISSUE THREAD

**Issue by unaiic** [kiudee/chess-tuning-tools#87]
If I wanted to stop/try the current best values from a tune, where can I find them? The log shows the values that are being tested at that time and also the confidence intervals, but I don't see the current "best values". How can I get them, and how many iterations are necessary to get "reliable" results (<10 parameters)? Thanks,

**Comment by kiudee** [comment]
If you set the parameter
```json
"result_every": 1
```
it will report the current optimum + confidence intervals every iteration.

If you run a 3 parameter tune with with informative parameters (i.e. they have a significant effect on playing strength), with 100 games per iteration (50 rounds), you can already converge in about 50 iterations. I know this since I recently ran a few experiments to optimize the default parameters:
![simple_regret](https://user-images.githubusercontent.com/564473/91307017-b4638180-e7ad-11ea-912e-17cf1b69e6ab.png)

If you opt to do less games per iteration, your parameters are less informative etc, then you likely need up to 300.

Now if you go with more parameters (5-10), I would strongly recommend to use at least 50 games per iteration. But in any case you should aim for at least 1000 iterations, since the landscape could be irregular and higher dimensional spaces are less well behaved.

All that being said, the current estimate for the global optimum should typically converge quickly to the promising regions. It only takes time to eek out the last Elo points, which of course requires a larger sample size.

**Comment by kiudee** [comment]
This could be an example configuration for such a tune.
```json
{
	"engines": [
		{
			"command": "sf",
			"fixed_parameters": {
                        ...
			}
		},
		{
			"command": "sf",
			"fixed_parameters": {
                         ...
			}
		}
	],
	"parameter_ranges": {
		"Param1": "Real(1.0, 5.0)",
                ...
	},
	"acq_function": "pvrs",
	"engine1_tc": "0.1",
        "engine2_tc": "0.05",
        "rounds": 50,
        "gp_burnin": 100,
        "gp_initial_burnin": 200,
        "n_initial_points": 8,
        "plot_every": 1,
        "result_every": 1,
        "adjudicate_draws": true,
        "adjudicate_resign": true,
        "adjudicate_tb": true,
        "tb_path": "C:\\syzygy",
        "opening_file": "..."
}
Set fixed parameters, parameter ranges, tb_path, opening_file and adjudication as you like.

**Comment by unaiic** [comment]
Okay, thank you :)

**Comment by kiudee** [comment]
Small addendum: If you want Stockfish to use tablebases, you need to specify so in the `fixed_parameters`:
```
			"fixed_parameters": {
				"Threads": 6,
				"Use NNUE": true,
				"EvalFile": "/path/to/engine/nn-82215d0fd0df.nnue",
				"SyzygyPath": "/path/to/tb"
			}
```

**Comment by Claes1981** [comment]
> Now if you go with more parameters (5-10), I would strongly recommend to use at least 50 games per iteration. 

Is there any other reason for this than some computation time  between iterations?  That is,  will the result be different compared to doing 25 times more iterations with 2 games per iteration? 


> All that being said, the current estimate for the global optimum should typically converge quickly to the promising regions. It only takes time to eek out the last Elo points, which of course requires a larger sample size.

**Comment by kiudee** [comment]
> Is there any other reason for this than some computation time between iterations? That is, will the result be different compared to doing 25 times more iterations with 2 games per iteration?

The main reason is indeed the computation time between iterations. But there is also an additional consideration. In high dimensions, it becomes more and more difficult to constrain the kernel hyperparameters using marginal prior distributions (see Michael Betancourt’s [excellent tutorial](https://betanalpha.github.io/assets/case_studies/gp_part3/part3.html#6_the_inevitable_curse_of_dimensionality)). By reducing the noise as much as possible, we are constraining the space of models consistent with the data, and make it easier for the model to fit the data. Ultimately reducing the number of iterations needed.

**Comment by unaiic** [comment]
@kiudee I wanted to start a new tune (with new parameters and engine binaries) but it didn't even start (after `tune local -c simple.json`):
```
Usage: tune [OPTIONS] COMMAND [ARGS]...
Try 'tune --help' for help.

Error: No such command 'local'.
```
It throws this error and I don't know what is wrong...

The simple.json file is this:
```
   {
       "engines": [
           {
               "command": "engine1",
               "fixed_parameters": {
                   "Threads": 1,
                   "EvalFile": "/home/corzounai/Desktop/tune/nn-82215d0fd0df.nnue"
               }
           },
           {
               "command": "engine2",
               "fixed_parameters": {
                   "Threads": 1,
                   "EvalFile": "/home/corzounai/Desktop/tune/nn-82215d0fd0df.nnue"
               }
           }
       ],
       "parameter_ranges": {
           "NNUEThreshold1": "Real(500, 600)",
           "NNUEThreshold2": "Real(100, 200)"
       },
       "engine1_tc": "1+0.01",
       "engine2_tc": "1+0.01",
       "opening_file": "noob_3moves.pgn",
       "concurrency": 2,
       "plot_every": 1,
       "result_every": 1,
       "rounds": 50
   }
```

**Comment by kiudee** [comment]
Could it be that there is a command collision with another `tune`? I am unfamiliar with that CLI interface.

**Comment by unaiic** [comment]
0.5.1

**Comment by kiudee** [comment]
I set up a new environment and installed `chess-tuning-tools==0.5.1`.
I get the following output:
```bash
$ tune --help
Usage: tune [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  local       Run a local tune.
  run-client  Run the client to generate games for distributed tuning.
  run-server  Run the tuning server for a given EXPERIMENT_FILE (json).
```

**Comment by unaiic** [comment]
Now it's working. I uninstalled and re-installed it. Thank you anyway!

**Comment by kiudee** [comment]
Glad it is working now - would have been stumped otherwise.

**Comment by unaiic** [comment]
![20200826-204904-34](https://user-images.githubusercontent.com/66777074/91344329-176d0c80-e7de-11ea-993b-016af85ad9a7.png)

These are the plots it generates. If I wanted to take the values and test the current best values, where would I have to look? Which are the best values, and which are the ones being tested?

**Comment by kiudee** [comment]
Typically you would use the red values (see [here](https://chess-tuning-tools.readthedocs.io/en/latest/faq.html#what-are-the-red-orange-dots-and-lines) for the FAQ regarding what they mean). They depict the current global optimum.

**Comment by kiudee** [comment]
The default parameters in 0.5.1 also use quite a lot of initial points. If you use predictive variance reduction search (the future default), you can use less initialization points:
```
"acq_function": "pvrs",
"n_initial_points": 8
```

**Comment by Eugenio-Bruno** [comment]
Apart from the global optimum, it might be useful to be able to ask the model to predict at arbitrary points. Say we're tuning Param1 and Param2. It would be great if we could do something along the lines of

```
$ tune local -c tune.json evaluate Param1=3 Param2=7
Got score -0.1236 +- 0.0442
```

Maybe the global optimum doesn't make as much intuitive sense as other completely different parameter, but if the tuner thinks those other parameters are also pretty good, maybe you can also try those when you submit a patch to fishtest/openbench...

**Comment by kiudee** [comment]
@Eugenio-Bruno indeed, I am planning to have a `query` command at some point with which you can ask the model different queries. Ideally without having to recompute the model every time.
