### ISSUE TITLE
Error when starting tune

### ISSUE THREAD

**Issue by unaiic** [kiudee/chess-tuning-tools#97]
I started a tune in my Windows machine, but I got this error:
`2020-09-15 09:22:08,274 INFO     Starting iteration 0
2020-09-15 09:22:08,274 INFO     Testing {'NNUEThreshold1': 359.19183560453405, 'NNUEThreshold2': 246.07183569591555, 't1': 196.7095197527795, 't2': 36.90845780741341, 't3': 94.53203711141416, 't4': 177.4301471320304, 't5': 93.62124746514169, 't6': 31.279151822481026}
2020-09-15 09:22:08,290 INFO     Start experiment
Traceback (most recent call last):
  File "c:\users\unaiic\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\unaiic\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\unaiic\AppData\Local\Programs\Python\Python38\Scripts\tune.exe\__main__.py", line 7, in <module>
  File "c:\users\unaiic\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\unaiic\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\unaiic\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\unaiic\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\unaiic\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\unaiic\appdata\local\programs\python\python38\lib\site-packages\tune\cli.py", line 425, in local
    out_exp, out_exp_err = run_match(**settings)
  File "c:\users\unaiic\appdata\local\programs\python\python38\lib\site-packages\tune\local.py", line 323, in run_match
    out = subprocess.run(string_array, capture_output=True)
  File "c:\users\unaiic\appdata\local\programs\python\python38\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\users\unaiic\appdata\local\programs\python\python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\users\unaiic\appdata\local\programs\python\python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified`

I have pip3 installed, chess-tuning-tools version 0.5.1, python 3.8.5, and cutechess. IDK what is wrong. Thank you!

EDIT: These are the files inside the tune directory: 2 engines, opening book, net and simple.json file:
`   {
       "engines": [
           {
               "command": "engine1",
               "fixed_parameters": {
                   "Threads": 1
               }
           },
           {
               "command": "engine2",
               "fixed_parameters": {
                   "Threads": 1
               }
           }
       ],
       "parameter_ranges": {
           "NNUEThreshold1": "Real(300, 700)",
           "NNUEThreshold2": "Real(50, 250)",
		   "t1": "Real(10, 200)",
		   "t2": "Real(10, 200)",
		   "t3": "Real(10, 200)",
		   "t4": "Real(10, 200)",
		   "t5": "Real(10, 200)",
		   "t6": "Real(10, 200)"
       },
       "engine1_tc": "1+0.01",
       "engine2_tc": "1+0.01",
       "opening_file": "noob_3moves.epd",
       "concurrency": 4,
       "plot_every": 1,
       "result_every": 1,
       "rounds": 50
   }`

**Comment by kiudee** [comment]
From the error message it looks like it is unable to call cutechess-cli. Is that available in the PATH?

**Comment by unaiic** [comment]
I suppose. I installed it from here (for Windows): https://github.com/cutechess/cutechess/releases

**Comment by kiudee** [comment]
As far as I remember I had to add cutechess to the environment variables:
![env_var](https://user-images.githubusercontent.com/564473/93203266-64486100-f754-11ea-8b43-25e30b23da4c.PNG)

**Comment by unaiic** [comment]
It throws me the error `cutechess-cli is not recognized as an internal or external command,
operable program or batch file.`, even though I have it installed and added to the environment variables...

**Comment by kiudee** [comment]
In order to refresh you typically need to restart the command prompt. If that does not work restarting Windows itself may be required.

**Comment by unaiic** [comment]
I tried bit it stll doesn't work :(

**Comment by kiudee** [comment]
What is the output when you type:
```
echo %PATH%
```

**Comment by unaiic** [comment]
C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Users\unaiic\AppData\Local\Programs\Python\Python38\Scripts\;C:\Users\unaiic\AppData\Local\Programs\Python\Python38\;C:\Users\unaiic\AppData\Local\Microsoft\WindowsApps;C:\Users\unaiic\AppData\Local\GitHubDesktop\bin

But I have both cutechess and cutechess-cli added to the environment variables. IDK why though...

**Comment by kiudee** [comment]
Hm, unsure what could be the reason that it is not showing up in PATH. Maybe try adding it into the *System variables* (in addition to *user variables*)?

**Comment by unaiic** [comment]
Yeah, I added the folder in both places (system and user), and restarted again; but it still doesn't work :(

**Comment by kiudee** [comment]
One idea I still have is to look for spaces in PATH. Try it with: `"C:\Program Files (x86)\cutechess"`

**Comment by unaiic** [comment]
I also have done that, but it still doesn't work nor does it appear after `echo %PATH%`. It shouldn't be that complicated...

**Comment by unaiic** [comment]
![Screenshot (51)](https://user-images.githubusercontent.com/66777074/93335217-637fff80-f826-11ea-88e3-fc866cec254f.png)

**Comment by kiudee** [comment]
Ah, you need to add the path to the variable called `Path`.

**Comment by unaiic** [comment]
Yeah, it was my fault. Now it works properly. Thank you!

**Comment by unaiic** [comment]
@kiudee Although it's not about this topic, when I start the tune it doesn't plot the results. This is my json file:
`   {
       "engines": [
           {
               "command": "engine1",
               "fixed_parameters": {
                   "Threads": 1
               }
           },
           {
               "command": "engine2",
               "fixed_parameters": {
                   "Threads": 1
               }
           }
       ],
       "parameter_ranges": {
	       "NNUEThreshold2": "Real(50, 250)",
               "NNUEThreshold1": "Real(300, 700)"
       },
       "engine1_tc": "1+0.01",
       "engine2_tc": "1+0.01",
       "opening_file": "noob_3moves.epd",
       "concurrency": 4,
       "plot_every": 1,
       "result_every": 1,
       "rounds": 50
   }`

**Comment by kiudee** [comment]
By default it runs an initialization phase with quasi-random points for 30 iterations. Then it starts fitting the model and outputting the landscape plots.
The setting can be changed using `"n_initial_points"`.
